# This file was generated by the {rix} R package v0.16.0 on 2025-08-17
# with following call:
# >rix(date = "2025-08-11",
#  > r_pkgs = c("languageserver",
#  > "tidyverse"),
#  > system_pkgs = c("uv"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-08-11.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      languageserver
      tidyverse;
  };
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      uv;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [  rpkgs   system_packages   ];
    shellHook = ''
      if [ ! -f pyproject.toml ]; then
        uv init --python 3.13.6
      fi
        uv add --requirements requirements.txt
      # Create alias so 'python' uses uv's environment
      alias python="uv run python"
    '';
  }; 
in
  {
    inherit pkgs shell;
  }
